name: Cpp Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build CXX bridge
      working-directory: cxx_example
      run: cargo build --release
      
    - name: Build examples
      working-directory: app
      run: |
         cmake .
         make

    - name: Run example
      working-directory: app/bin
      run: ./test
