name: Generate API documents

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install doxygen -y
      shell: bash

    - name: Rustdoc
      working-directory: rs_example
      run: cargo doc --no-deps

    - name: Deploy
      uses: actions/upload-pages-artifact@v1
      with:
        path: target/doc

    - name: Build cxxbridge
      working-directory: cxx_example
      run: |
         cargo build --release

    - name: Doxygen
      working-directory: target/cxxbridge
      run: doxygen ../../cxx_example/Doxyfile
