name: Rust Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build

    - name: Set Toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Run check
      run: cargo check

    - name: Run rustfmt    
      run: cargo fmt --all -- --check
      
    - name: Run clippy
      env:
        RUSTFLAGS: "-Dwarnings"        
      run: cargo clippy --all-targets --all-features

    - name: Run tests
      run: cargo test
